### ISSUE TITLE
Export Gama models in a p2 repository

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.models#1]
The current mode stored in this repository should be available from the GUI  using a p2 repository.

@RoiArthurB can you have a look at it?

**Comment by RoiArthurB** [comment]
Not sure it's necessary anymore, closing it as stale state. 

As the development been, everything is saved on the branch `plugins-builder` with maven ready to compile and publish everything (on Github Pages, on the branch `p2-deploy`). Only remaining issue is that generated plugins doesn't bring models in any default GAMA folder... But, as discussed with Arnaud, downloading the root repository as a zip and importing it inside workspace is probably simplier/faster.

Please re-open if needed again.
